### ISSUE TITLE
Implement MemoryManager and MemoryPool from System.Buffers

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nxrighthere/Smmalloc-CSharp#1]
Seems it is .NET Standard API for allocators.

https://gist.github.com/GrabYourPitchforks/8efb15abbd90bc5b128f64981766e834

**Comment by nxrighthere** [comment]
My goal with this project is to keep it as lightweight and simple as possible. This is the direct replacement for unmanaged [heap allocator](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.allochglobal) with the tiny wrapper for .NET.
